name: Build and Release

on:
  push:
    branches:
      - main # или master, в зависимости от вашей основной ветки

jobs:
  release:
    runs-on: windows-latest # Собираем на Windows

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Используем стабильную LTS-версию для сборки

      - name: Install dependencies
        run: npm install

      - name: Build and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Секретный токен для публикации
        run: npm run dist -- --publish always